# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 906c829d4e99997e2cfd44c945349b9810115a5d49891e6e189eca19214fdd1c706cba71e6978aca2e6d1d032b3899219dd9200e323d31268b4b6dd307512fa9

test:
  secret_key_base: 2dc8b16caaa74e201f0214304489d82dc6633958dfa0eac6dc92afd5c381da0ba4e239d9f1b702fb398f499a1fac54c259379aaa454dc64fc71165ade1ff11a2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
